version: 2
#compilo
jobs:
  build:
    docker:
      - image: circleci/php:7.3.5
    working_directory: ~/project/Code
    steps:
      - run:
          command: mkdir tmpdir && cd tmpdir
          name: Making directory
      - run:
          command: git clone https://github.com/rospino74/StudentOS
          name: Cloning repository
      - run:
          command: cd Code
          name: Get into Code Folder
      - run:
          command: php index.php
          name: Running index.php
      - run:
          command: php home.php
          name: Running home.php
