version: 2
#compilo
jobs:
  build:
    docker:
      - image: circleci/php:7.3.5
    working_directory: ~/project/Code
    steps:
      - run:
          command: git clone https://github.com/rospino74/StudentOS tmpdir
          name: Cloning repository into tmpdir
      - run:
          command: cd tmpdir/Code && ls
          name: Listing files
      - run:
          command: cd tmpdir/Code && php index.php
          name: Running index.php
      - run:
          command: cd tmpdir/Code && php check.php
          name: Running check.php
