version: 2

#compilo
jobs:
  build:
    docker:
      - image: circleci/php:7.3.5
    working_directory: ~/project/Code
    steps:
      - run:
          command: echo $PATH
          name: listing directory and checking path
