version: 2
#compilo
jobs:
  build:
    docker:
      - image: circleci/php:7.3.5
      - image: circleci/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: studentoa
            MYSQL_USER: user
            MYSQL_PASSWORD: passw0rd

    working_directory: ~/project/
    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo MySQL is ready! && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo rm /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
            sudo apt-get update
            echo "Now install mysql: " & sudo apt install -y mysql-client
           
      #cloning code
      - run:
          command: git clone https://github.com/rospino74/StudentOS tmpdir
          name: Cloning repository into tmpdir
          
      #adding data
      - run:
          command: mysql -h 127.0.0.1 -u root studentoa < tmpdir/Code/admin/builder.sql
          name: Adding data to db
          
      #renaming config file
      - run:
          command: cd tmpdir/Code/admin && mv template.db.config.php db.config.php
          name: Renaming config file
          
      #testing
      - run:
          command: cd tmpdir/Code && php index.php
          name: Running index file
      - run:
          command: cd tmpdir/Code/classroom && php index.php?class=class1
          name: Running index file
